### ISSUE TITLE
Fix distributed associations - Include adapter authorization and reporting of "benign" errors

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/graphql-server-model-codegen#101]
For "root" resolvers we implemented an additional step that checks whether a user has authorization to use a certain adapter. The resolvers passes only the authorized adapters to the distributed data model (DDM). Furthermore, errors reported by some adapters are gathered in `context.benignErrors` and reported in the standard GraphQL way, i.e. data along with errors might be sent back to the user.

This approach needs to be reproduced for the resolvers of distributed associations. Currently this is not yet done.

**Comment by asishallab** [comment]
Note that this involves the following API endpoints (functions) in the resolver:

* to-one association: Identify responsible adapter and check whether the user is authorized to use it
* to-many association - connection: Filter registered adapters for those the user is authorized to use.
* to-many association - count: Filter registered adapters for those the user is authorized to use.

**Comment by coeit** [comment]
Problems:

- currently we don't include all associated models in the resolver. We would need that to check the registered adapters for the associated model.  
- for to_one associations. Currently when resolving a `to_one` association e.g. a book has one author, the resolver will call a **instance** method `authorImpl(search)` in the book DDM. This method will then look up the associated record via the `readById` function of the associated model, in this case `models.person.readById(this.internalPersonId)` and the internalId of the instance.
The resolver does not know which is the responsible Adapter for the query

**Comment by asishallab** [comment]
Thanks @coeit for your comment. Responding to your second remark. The distributed data model knows the name of its `idAttribute`, use that name to extract the respective `id` from the provided search arguments and then invoke the `getAdapterForIri` function accordingly.
