### ISSUE TITLE
Fix return type of bulkCreate (CSV Upload)

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/graphql-server-model-codegen#131]
Currently the return type as in the GraphQL schema is an Array of records. We changed this to be a background job that sends an email informing the user about success or (validation) errors. 

Adjust the return type to `String` and send an informative message like 
`Bulk import of ${dataModel.name} records started. You will be send an email to ${user.email} informing you about success or errors.`

**Comment by vsuaste** [comment]
Done. Commit: [#70d5d5](https://github.com/Zendro-dev/graphql-server-model-codegen/commit/70d5d523466a8d6fb5fd298cb1b438aea0e9000f)
