### ISSUE TITLE
Refactor multiple counts in <modelNamePlurar> and <modelNamePluralConnection> root resolvers

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/graphql-server-model-codegen#142]
Currently the count of records matching a search query is carried out multiple times. Once inside the resolver to determine the number of records to subtract from the current record limit and again inside the model layer when building the result object of limit-offset-based or cursor-based pagination. This is inefficient and should be refactored.

### Refactor

Store the result of the count in the resolver layer in a variable and pass that variable to the respective model layer function(s). 
Use default values for function arguments:

```javascript
var count = function(searchArg) { return searchArg + 1 }
var readAllFancy = function(searchArg, countResult = count(searchArg) ) { 
  console.log(`countResult is: ${countResult}`)
}
```

### Check field resolvers and related model layer implementations of associations

Check whether this improvement will be automatically used by associations, too.

**Comment by asishallab** [comment]
[This blog post](https://medium.com/dailyjs/named-and-optional-arguments-in-javascript-using-es6-destructuring-292a683d5b4e) about named arguments and default values in Javascript maybe helps.

**Comment by coeit** [comment]
We will refactor _readMany_ (`readAllCursor`, `readAll`) functions to not do a count. This will impact the implementations the respective functions as well as the reduction of the record limit, currently done in `checkAndAdjustRecordLimit` (resolver).

Sketch of the new design is maintained in [hackMD document](https://hackmd.io/qMoS-UvISc2ZrJtfcxurXw?view).
